# Generated by Django 5.2.4 on 2025-07-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='пользователь')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('date', models.DateField(verbose_name='дата отпраки')),
                ('time', models.TimeField(verbose_name='время отправки')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
            },
        ),
        migrations.AlterModelOptions(
            name='taskmanager',
            options={'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
    ]
